[package]
name = "fedimint-wasm-tests"
version = { workspace = true }
edition = "2021"
license = "MIT"
description = "Wasm tests for the fedimint."
publish = false

[lib]
crate-type = ["rlib", "cdylib"]
name = "fedimint_wasm_tests"
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true }
fedimint-api-client = { workspace = true }
fedimint-client = { workspace = true }
fedimint-core = { workspace = true }
fedimint-ln-client = { workspace = true }
fedimint-ln-common = { workspace = true }
fedimint-mint-client = { workspace = true }
fedimint-mint-common = { workspace = true }
fedimint-wallet-client = { workspace = true }
futures = { workspace = true }
gloo-net = "0.6.0"
js-sys = "0.3.69"
rand = { workspace = true }
ring = { workspace = true, features = ["wasm32_unknown_unknown_js"] }
wasm-bindgen = "=0.2.92"                                              # must match the nix provided wasm-bindgen-cli version
wasm-bindgen-futures = "0.4.42"
wasm-bindgen-test = "0.3.42"
