[package]
name = "fedimint-gateway-cli"
version = { workspace = true }
edition = "2021"
license = "MIT"
readme = "../../README.md"
description = "CLI tool to control lightning gateway"
repository = "https://github.com/fedimint/fedimint"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "tokio_unstable"]

[features]
default = ["tor"]
tor = ["ln-gateway/tor"]

[[bin]]
name = "gateway-cli"
path = "src/main.rs"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
bitcoin = { workspace = true }
clap = { version = "4.5.16", features = [
    "derive",
    "std",
    "help",
    "usage",
    "error-context",
    "suggestions",
], default-features = false }
clap_complete = "4.5.23"
fedimint-core = { workspace = true }
fedimint-logging = { workspace = true }
fedimint-mint-client = { workspace = true }
lightning-invoice = { workspace = true }
ln-gateway = { workspace = true, default-features = false }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true, default-features = false, features = [
    "log",
    "attributes",
    "std",
] }
url = { workspace = true, features = ["serde"] }

[build-dependencies]
fedimint-build = { workspace = true }
